### ISSUE TITLE
The --yaml parser doesn't run for me on ubuntu 18.04 when using the deb or the .tar.gz file

### ISSUE THREAD

**Issue by bryder** [kellyjonbrazil/jc-packaging#1]
For these files
```
jc-1.14.1-1.x86_64.deb
jc-1.14.1-linux-x86_64.tar.gz
```

For this test
```bash
 printf 'blah:\n  thing: stuff' | ./jc -d --yaml
````
I get this error
```text
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "jc.cli", line 456, in main
  File "jc.parsers.yaml", line 137, in parse
  File "ruamel.yaml.main", line 89, in __init__
  File "ruamel.yaml.main", line 633, in official_plug_ins
NameError: name '__file__' is not defined
```

The pypi install is fine which is why I think it's a packaging bug - not a bug in jc as such.
 But I'm happy to open an issue on the jc project if you prefer.

I'm not sure how you would fix it since ruamel.yaml does this

```python
    # helpers
    def official_plug_ins(self):
        # type: () -> Any
        bd = os.path.dirname(__file__)
        gpbd = os.path.dirname(os.path.dirname(bd))
        res = [x.replace(gpbd, "")[1:-3] for x in glob.glob(bd + '/*/__plug_in__.py')]
        return res
```

**Comment by bryder** [comment]
I see this isn't an uncommon problem. 

https://github.com/indygreg/PyOxidizer/issues/69

So it's a ruamel.yaml problem.

**Comment by kellyjonbrazil** [comment]
Thank you for reporting this. I'll need to dig into this a little more to see if there is anything I can do here besides open an issue on ruamel.yaml.

I wonder if I should stop building these Debian packages now that it is available directly from Debian: https://packages.debian.org/sid/all/jc/download

Could you test and see if that DEB package works for 18.04?

**Comment by bryder** [comment]
I tried out jc_1.14.3-1_all.deb and it works as expected. 

It's not oxidized so it's using the system libraries so there's no problem with the ``` __file__``` attribute.

I really like the single binary approach (keeps the go lang fans quiet :-) but I understand it's not a problem with jc. 

Thanks for the response!

**Comment by kellyjonbrazil** [comment]
Right on - I'll open an issue with ruamel.yaml and see if they can remove the `__file__` dependency or maybe fail gracefully if it doesn't exist or returns `None`.  If that's possible, then I could package up `jc` v1.14.3 binaries, RPM, and DEB with that fix.

**Comment by kellyjonbrazil** [comment]
Actually, looks like this issue was already reported: https://sourceforge.net/p/ruamel-yaml/tickets/324/

I'll add on to the ticket.

**Comment by kellyjonbrazil** [comment]
Anthon provided a potential workaround that I'll try out:

It is an easy fix if the packaging doesn't need the plug-ins. In that case it is a question of catching the NameError and returning the empty list. It is scheduled for 0.17.0.

Until then you can of course do something like:
```
ruamel.yaml.YAML.official_plug_ins = lambda a: []
```
before instantiating `YAML()`

If that works, I can package it up shortly.

**Comment by kellyjonbrazil** [comment]
I updated the packages to v1.14.4, which I believe fixes this issue. Could you test on your end to make sure everything is ok?

Thanks!

**Comment by bryder** [comment]
I tested jc-1.14.4-linux-x86_64.tar.gz and it works now.

Thanks very much for your efforts!

**Comment by kellyjonbrazil** [comment]
Awesome, thanks!
